---
  # tasks file for influxdb
- name: apt ~> add key
  apt_key:
    url: http://repos.influxdata.com/influxdb.key
    state: present

- name: apt ~> add influxdb repo
  apt_repository:
    repo: "deb http://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: "influxdb"
